app/routes.php
<?php

Route::resource('admin/seo', 'AdminSeoController');

// Routes for the menu admin
Route::group(array('prefix' => 'admin/menu'), function()
{
    // Showing the admin for the menu builder and updating the order of menu items
    Route::get('/', 'AdminMenuController@getIndex');
    Route::post('/', 'AdminMenuController@postIndex');

    Route::post('new', 'AdminMenuController@postNew');
    Route::post('delete', 'AdminMenuController@postDelete');

    Route::get('edit/{id}', 'AdminMenuController@getEdit');
    Route::post('edit/{id}', 'AdminMenuController@postEdit');
});

// This is the route for the Backbone pagination
Route::get('api/products', 'ApiProductsController@getIndex');

// Route for Homepage - displays all products from the shop
Route::get('/', function()
{
	$products = Product::all();
	$categories = Category::all();

	return View::make('index', array(
		'products'		=> $products, 
		'categories' 	=> $categories
	));
});

// Route that shows an individual product by its slug
Route::get('products/{slug}', function($slug)
{
	$product 	= Product::whereSlug($slug)->firstOrFail();
	$categories = Category::all();
	$seo 		= $product->seo()->first();

	// Get all reviews that are not spam for the product and paginate them
	$reviews = $product->reviews()->with('user')->approved()->notSpam()->orderBy('created_at','desc')->paginate(100);

	return View::make('products.single', array(
		'product'	=> $product,
		'reviews'	=> $reviews, 
		'categories'=> $categories,
		'seo'		=> $seo
	));
});

// Route that handles submission of review - rating/comment
Route::post('products/{slug}', array('before'=>'csrf', function($slug)
{
	$input = array(
		'comment' => Input::get('comment'),
		'rating'  => Input::get('rating')
	);
	// instantiate Rating model
	$review = new Review;

	// Validate that the user's input corresponds to the rules specified in the review model
	$validator = Validator::make( $input, $review->getCreateRules());

	// If input passes validation - store the review in DB, otherwise return to product page with error message 
	if ($validator->passes()) {
		$review->storeReviewForProduct($slug, $input['comment'], $input['rating']);
		return Redirect::to('products/'.$slug.'#reviews-anchor')->with('review_posted',true);
	}
	
	return Redirect::to('products/'.$slug.'#reviews-anchor')->withErrors($validator)->withInput();
}));

// Route that shows an individual category by its slug
Route::get('categories/{slug}', function($slug)
{
	$category = Category::whereSlug($slug)->firstOrFail();
	$categories = Category::all();
	$seo 		= $category->seo()->first();

	return View::make('categories.single', array(
		'category'	=> $category,
		'categories'=> $categories,
		'seo'		=> $seo
	));
});

Route::get('api/search', 'ApiSearchController@index');

app/models/Product.php
<?php

class Product extends Eloquent
{
	// Relationships 
	public function reviews()
	{
	    return $this->hasMany('Review');
	}

	public function categories()
	{
		return $this->belongsToMany('Category');
	}

	public function seo()
	{
	    return $this->morphMany('Seo', 'seoble');
	}

	// Getters
	public function getIconAttribute()
	{
		return $this->attributes['icon'] ? url($this->attributes['icon']) : 'http://placehold.it/20x20';
	}

	public function getBannerAttribute()
	{
		return $this->attributes['banner'] ? url($this->attributes['banner']) : 'http://placehold.it/300x240';
	}

	// Scopes

	public function scopePublished($query)
	{
	   	return $query->where('published', true);
	}

	public function scopePopular($query)
	{
	   	return $query->published()->orderBy('rating_cache','desc');
	}

	public function scopeNewest($query)
	{
	   	return $query->published()->orderBy('created_at','desc');
	}

	public function scopeByname($query)
	{
	   	return $query->published()->orderBy('name','asc');
	}

	// The way average rating is calculated (and stored) is by getting an average of all ratings, 
	// storing the calculated value in the rating_cache column (so that we don't have to do calculations later)
	// and incrementing the rating_count column by 1

    public function recalculateRating($rating)
    {
    	$reviews = $this->reviews()->notSpam()->approved();
	    $avgRating = $reviews->avg('rating');
		$this->rating_cache = round($avgRating,1);
		$this->rating_count = $reviews->count();
    	$this->save();
    }
}

app/models/Review.php
<?php

class Review extends Eloquent
{

    // Validation rules for the ratings
    public function getCreateRules()
    {
        return array(
            'comment'=>'required|min:10',
            'rating'=>'required|integer|between:1,5'
        );
    }

    // Relationships
    public function user()
    {
        return $this->belongsTo('User');
    }

    public function product()
    {
        return $this->belongsTo('Product');
    }

    // Scopes
    public function scopeApproved($query)
    {
       	return $query->where('approved', true);
    }

    public function scopeSpam($query)
    {
       	return $query->where('spam', true);
    }

    public function scopeNotSpam($query)
    {
       	return $query->where('spam', false);
    }

    // Attribute presenters
    public function getTimeagoAttribute()
    {
    	$date = \Carbon\Carbon::createFromTimeStamp(strtotime($this->created_at))->diffForHumans();
    	return $date;
    }

    // this function takes in product ID, comment and the rating and attaches the review to the product by its ID, then the average rating for the product is recalculated
    public function storeReviewForProduct($slug, $comment, $rating)
    {
        $product = Product::whereSlug($slug)->firstOrFail();

        //$this->user_id = Auth::user()->id;
        $this->comment = $comment;
        $this->rating = $rating;
        $product->reviews()->save($this);

        // recalculate ratings for the specified product
        $product->recalculateRating($rating);
    }
}

app/controllers/Api/ProductsController.php
<?php

class ApiProductsController extends \BaseController {

    public function getIndex()
    {
        // Get the number of items to show per page (defaults to 6 items)
        $perPage = e(Input::get('per_page','6'));

        // Get the index of the current page (defaults to the first page)
        $page = e(Input::get('page','1'));

        // Get the sorting parameter (defaults to popular)
        $sort = e(Input::get('sort','popular'));

        // Calculate the offset of the items
        $offset = $page*$perPage-$perPage;

        // The count of items will be updated from the query
        $count = 0;

        switch ($sort) {
          case 'date':
            $sortedProducts = Product::newest();
            break;
          case 'name':
            $sortedProducts = Product::byname();
            break;
          default:
            $sortedProducts = Product::popular();
            break;
        }

        // Get the count
        $count = $sortedProducts->count();

        // Retrieve the products using Laravel's Eloquent ORM methods
        $products = $sortedProducts->take($perPage)->offset($offset)->get(array('slug','rating_cache','name','short_description','icon','banner','pricing'));

        // Return the results as JSON data
        return Response::json(array(
          'data'=>$products->toArray(),
          'total' => $count
        ));
    }
}

app/views/products/single.blade.php
@extends('layout')

@section('title')
{{{ $seo->title or 'Viewing Product '.$product->name }}}
@endsection

@section('description')
{{{ $seo->description or 'My great product'}}}
@endsection

@section('keywords')
{{{ $seo->keywords or 'default, keywords, for, my, product' }}}
@endsection

@section('scripts')
  {{HTML::script('js/expanding.js')}}
  {{HTML::script('js/starrr.js')}}

  <script type="text/javascript">
    $(function(){

      // initialize the autosize plugin on the review text area
      $('#new-review').autosize({append: "\n"});

      var reviewBox = $('#post-review-box');
      var newReview = $('#new-review');
      var openReviewBtn = $('#open-review-box');
      var closeReviewBtn = $('#close-review-box');
      var ratingsField = $('#ratings-hidden');

      openReviewBtn.click(function(e)
      {
        reviewBox.slideDown(400, function()
          {
            $('#new-review').trigger('autosize.resize');
            newReview.focus();
          });
        openReviewBtn.fadeOut(100);
        closeReviewBtn.show();
      });

      closeReviewBtn.click(function(e)
      {
        e.preventDefault();
        reviewBox.slideUp(300, function()
          {
            newReview.focus();
            openReviewBtn.fadeIn(200);
          });
        closeReviewBtn.hide();
        
      });

      // If there were validation errors we need to open the comment form programmatically 
      @if($errors->first('comment') || $errors->first('rating'))
        openReviewBtn.click();
      @endif

      // Bind the change event for the star rating - store the rating value in a hidden field
      $('.starrr').on('starrr:change', function(e, value){
        ratingsField.val(value);
      });
    });
  </script>
@stop

@section('styles')
  <style type="text/css">

     /* Enhance the look of the textarea expanding animation */
     .animated {
        -webkit-transition: height 0.2s;
        -moz-transition: height 0.2s;
        transition: height 0.2s;
      }

      .stars {
        margin: 20px 0;
        font-size: 24px;
        color: #d17581;
      }
  </style>
@stop

@section('content')
    <div class="row">
        <div class="col-md-3">
          @include('partials.sidebar.categories', array('categories' => $categories,'current' => 0))
        </div>
        <div class="col-md-9">
            <div class="thumbnail">
              <img src="http://placehold.it/820x320" alt="">
              <div class="caption-full">
                  <h4 class="pull-right">${{ number_format($product->pricing, 2);}}</h4>
                  <h4><a href="{{url('products/'.$product->slug)}}">{{$product->name}}</a></h4>
                  <p>{{$product->short_description}}</p>
                  <p>{{$product->long_description}}</p>

                  <p>
                    @foreach($product->categories as $category)
                      <span class="glyphicon glyphicon-tag"></span> <a href="{{ url('categories/'.$category->slug) }}">{{{ $category->name }}} </a>
                    @endforeach
                  </p>
              </div>
              <div class="ratings">
                  <p class="pull-right">{{$product->rating_count}} {{ Str::plural('review', $product->rating_count);}}</p>
                  <p>
                    @for ($i=1; $i <= 5 ; $i++)
                      <span class="glyphicon glyphicon-star{{ ($i <= $product->rating_cache) ? '' : '-empty'}}"></span>
                    @endfor
                    {{ number_format($product->rating_cache, 1);}} stars
                  </p>
              </div>
            </div>
            <div class="well" id="reviews-anchor">
              <div class="row">
                <div class="col-md-12">
                  @if(Session::get('errors'))
                    <div class="alert alert-danger">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                       <h5>There were errors while submitting this review:</h5>
                       @foreach($errors->all('<li>:message</li>') as $message)
                          {{$message}}
                       @endforeach
                    </div>
                  @endif
                  @if(Session::has('review_posted'))
                    <div class="alert alert-success">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5>Your review has been posted!</h5>
                    </div>
                  @endif
                  @if(Session::has('review_removed'))
                    <div class="alert alert-success">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5>Your review has been removed!</h5>
                    </div>
                  @endif
                </div>
              </div>
              <div class="text-right">
                <a href="#reviews-anchor" id="open-review-box" class="btn btn-success btn-green">Leave a Review</a>
              </div>
              <div class="row" id="post-review-box" style="display:none;">
                <div class="col-md-12">
                  {{Form::open()}}
                  {{Form::hidden('rating', null, array('id'=>'ratings-hidden'))}}
                  {{Form::textarea('comment', null, array('rows'=>'5','id'=>'new-review','class'=>'form-control animated','placeholder'=>'Enter your review here...'))}}
                  <div class="text-right">
                    <div class="stars starrr" data-rating="{{Input::old('rating',0)}}"></div>
                    <a href="#" class="btn btn-danger btn-sm" id="close-review-box" style="display:none; margin-right:10px;"> <span class="glyphicon glyphicon-remove"></span>Cancel</a>
                    <button class="btn btn-success btn-lg" type="submit">Save</button>
                  </div>
                {{Form::close()}}
                </div>
              </div>

              @foreach($reviews as $review)
              <hr>
                <div class="row">
                  <div class="col-md-12">
                    @for ($i=1; $i <= 5 ; $i++)
                      <span class="glyphicon glyphicon-star{{ ($i <= $review->rating) ? '' : '-empty'}}"></span>
                    @endfor

                    {{ $review->user ? $review->user->name : 'Anonymous'}} <span class="pull-right">{{$review->timeago}}</span> 
                    
                    <p>{{{$review->comment}}}</p>
                  </div>
                </div>
              @endforeach
              {{ $reviews->links(); }}
            </div>
        </div>

    </div>
@stop